FROM debian:bullseye

RUN apt-get update && apt-get install -y \
        curl \
        git \
        build-essential \
        cmake \
        jq \
        nano \
        python3-pip \
        mosquitto-clients &&
        pip3 install paho-mqtt

ADD sources/ /opt/
ADD config/ /etc/inverter/

RUN cd /opt/inverter-cli && \
    mkdir bin && cmake . && make && mv inverter_poller bin/

HEALTHCHECK \
    --interval=30s \
    --timeout=10s \
    --start-period=1m \
    --retries=3 \
  CMD /opt/healthcheck

WORKDIR /opt/inverter-mqtt
ENTRYPOINT ["/bin/bash", "/opt/inverter-mqtt/entrypoint.sh"]
